const TELEGRAM_CONFIG_KEY = 'sales_reports_telegram_config_v1';

export interface TelegramConfig {
  botToken: string;
  chatId: string;
  enabled: boolean;
  autoDailySummary: boolean;
}

export function getTelegramConfig(): TelegramConfig {
  if (typeof window === 'undefined') {
    return {
      botToken: process.env.TELEGRAM_BOT_TOKEN || '',
      chatId: process.env.TELEGRAM_CHAT_ID || '',
      enabled: Boolean(process.env.TELEGRAM_BOT_TOKEN),
      autoDailySummary: false,
    };
  }

  const raw = localStorage.getItem(TELEGRAM_CONFIG_KEY);
  if (!raw) {
    return {
      botToken: '',
      chatId: '',
      enabled: false,
      autoDailySummary: false,
    };
  }
  try {
    return JSON.parse(raw);
  } catch (e) {
    return { botToken: '', chatId: '', enabled: false, autoDailySummary: false };
  }
}

export function saveTelegramConfig(config: TelegramConfig) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(TELEGRAM_CONFIG_KEY, JSON.stringify(config));
}

/**
 * Send a message via Telegram Bot API
 */
export async function sendTelegramMessage(message: string, overrideChatId?: string, overrideToken?: string): Promise<{ success: boolean; error?: string }> {
  const config = getTelegramConfig();
  const botToken = overrideToken || config.botToken || process.env.TELEGRAM_BOT_TOKEN;
  const chatId = overrideChatId || config.chatId || process.env.TELEGRAM_CHAT_ID;

  if (!botToken || !chatId) {
    return {
      success: false,
      error: 'Telegram Bot Token and Chat ID must be configured in Settings.',
    };
  }

  try {
    const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: message,
        parse_mode: 'HTML',
        disable_web_page_preview: false,
      }),
    });

    const data = await res.json();
    if (data.ok) {
      return { success: true };
    } else {
      return { success: false, error: data.description || 'Telegram API error' };
    }
  } catch (err: any) {
    return { success: false, error: err.message || 'Network error sending to Telegram' };
  }
}

/**
 * Format daily financial summary for Telegram
 */
export function formatDailyTelegramSummary(params: {
  date: string;
  ordersCount: number;
  totalQty: number;
  totalNabtaBill: number;
  totalClientBill: number;
  jahedBalance: number;
  ordersPaid: number;
  expensesPaid: number;
  nabtaYesterdayBalance: number;
  nabtaTodayBalance: number;
  reportLink?: string;
}): string {
  const {
    date,
    ordersCount,
    totalQty,
    totalNabtaBill,
    totalClientBill,
    jahedBalance,
    ordersPaid,
    expensesPaid,
    nabtaYesterdayBalance,
    nabtaTodayBalance,
    reportLink,
  } = params;

  return `📊 <b>NABTA & JAHED DAILY SALES REPORT</b>
📅 <b>Date:</b> <code>${date}</code>

📦 <b>Orders:</b> ${ordersCount} orders (${totalQty} units)
💰 <b>Nabta Bill (Cost):</b> AED ${totalNabtaBill.toFixed(2)}
💵 <b>Client Bill:</b> AED ${totalClientBill.toFixed(2)}
🟢 <b>Jahed Balance (No Pay):</b> <b>AED ${jahedBalance.toFixed(2)}</b>

══════════════════════
<b>DAY BALANCE CARRY-FORWARD:</b>
• <b>Yesterday Balance:</b> AED ${nabtaYesterdayBalance.toFixed(2)}
• <b>(+) Client Payments:</b> AED ${ordersPaid.toFixed(2)}
• <b>(−) Total Expenses:</b> AED ${expensesPaid.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━━━
🏁 <b>Nabta Today Balance:</b> <b>AED ${nabtaTodayBalance.toFixed(2)}</b>
══════════════════════
${reportLink ? `🔗 <b>Shareable Nabta Report Link:</b>\n<a href="${reportLink}">${reportLink}</a>\n` : ''}
<i>Generated by Sales & Payment Reports</i>`;
}
